server:
  port: 8080

spring:
  datasource:
    url: ${TEST_DB:jdbc:h2:mem:testdb}
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  security:
    #    oauth2 configurations
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:test-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:test-client-secret}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            #/login/oauth2/code/google
            scope:
              - email
              - profile
              - openid
          github:
            client-id: ${GITHUB_CLIENT_ID:test-client-id}
            client-secret: ${GITHUB_CLIENT_SECRET:test-client-secret}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            #/login/oauth2/code/github
            scope:
              - user:email
              - read:user

security:
  jwt:
    secret: ${JWT_SECRET:9b14f5e214dbbb19a11d93714c20e9e0f91bd2920e423a9233f939dc881fa74a}
    issuer: ${JWT_ISSUER:auth-backend}
    access-ttl-seconds: ${JWT_ACCESS_TTL_SECONDS:3600}       # 60 minutes
    refresh-ttl-seconds: ${JWT_REFRESH_TTL_SECONDS:1209600}  # 14 days
    refresh-cookie-name: ${JWT_REFRESH_COOKIE_NAME:refresh_token}
    cookie-http-only: ${JWT_COOKIE_HTTP_ONLY:false}
    cookie-secure: ${JWT_COOKIE_SECURE:false}
    cookie-same-site: ${JWT_COOKIE_SAME_SITE:Lax}
    cookie-domain: ${JWT_COOKIE_DOMAIN:localhost}

app:
  auth:
    frontend:
      success-redirect: http://localhost:5173/oauth/success
      failure-redirect: http://localhost:5173/oauth/failure
